### ISSUE TITLE
Why crates can not be imported?

### ISSUE THREAD

**Issue by Eh2406** [Eh2406/pubgrub-crates-benchmark#4]
Some version in the crates.io index fail to convert into a `Cargo::Summary` we filtered these versions [out here](https://github.com/Eh2406/pubgrub-crates-benchmark/blob/5362f29e63b26f521e7693544616de0d455f14bf/src/main.rs#L14). What are these versions? Why can't they be imported? Most do they work with Cargo's CLI? If they work with the CLI but not with this program we have a bug. If there just FUBAR and do not work at all then we are correctly ignoring them.

**Comment by tareknaser** [comment]
Here are the crates that fail to convert into a `Cargo::Summary`. I gathered this information using this [branch](https://github.com/tareknaser/pubgrub-crates-benchmark/tree/import_error).

| crate_name           | version                                                                      | error                                                                                                                                                                                                               | commit                                                                                                        |
| -------------------- | ---------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
| futures-util-preview | [0.3.0-alpha.4](https://crates.io/crates/futures-util-preview/0.3.0-alpha.4) | [feature `compat` includes `futures01` which is neither a dependency nor another feature](https://github.com/rust-lang/crates.io-index/blob/c29c4baa7a9d2b16015dbb2040e556b3240d5716/fu/tu/futures-util-preview#L6) | [a54604f](https://github.com/rust-lang/futures-rs/tree/a54604f31741ab44036c2a65b66caf348a3b3dde/futures-util) |
| fuels-programs       | [0.37.0](https://crates.io/crates/fuels-programs/0.37.0)                     | [feature `std` includes `fuels-test-helpers/std`, but `fuels-test-helpers` is not a dependency](https://github.com/rust-lang/crates.io-index/blob/7369a7e31df805389b3f5320aec7757b7fc48605/fu/el/fuels-programs#L7) | [7d15913](https://github.com/FuelLabs/fuels-rs/tree/7d159136ff538ebc6ee77189d300caca302ebde2)<br>             |
| fuels-signers        | [0.37.0](https://crates.io/crates/fuels-signers/0.37.0)                      | [feature `std` includes `fuels-test-helpers/std`, but `fuels-test-helpers` is not a dependency](https://github.com/rust-lang/crates.io-index/blob/7369a7e31df805389b3f5320aec7757b7fc48605/fu/el/fuels-signers#L52) | [7d15913](https://github.com/FuelLabs/fuels-rs/tree/7d159136ff538ebc6ee77189d300caca302ebde2)<br>             |
| ontio-codegen        | [0.2.0](https://crates.io/crates/ontio-codegen/0.2.0)                        | [feature `mock` includes `ontio-std/mock`, but `ontio-std` is not a dependency](https://github.com/rust-lang/crates.io-index/blob/7369a7e31df805389b3f5320aec7757b7fc48605/on/ti/ontio-codegen#L2)                  | can't find it - maybe force pushed?                                                                           |

These crates don’t work with Cargo’s CLI. For example, when I tried adding `ontio-codegen = "=0.2.0"` to an empty `Cargo.toml` file, I got this error:
```shell
error: failed to select a version for the requirement `ontio-codegen = "=0.2.0"`
candidate versions found which didn't match: 0.2.1, 0.1.0
location searched: crates.io index
```
The same thing happened with the other crates in the table. 

I’ve added the links to the crates on crates.io in the version column and to the index on GitHub in the error column, respectively.

That said, I think it’s right that we’re ignoring them.

**Comment by Eh2406** [comment]
After your thorough investigation, I no longer consider this an issue. We seem to be handling things correctly!
